config/routes.rb
Rails.application.routes.draw do

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'users#new'

  root :to => 'sessions#new'

  resources :addresses
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  def index
    @countries = Address.distinct(:country)
  end

  def show
    @addresses = Address.where(:country => params[:id]).in(:user_search => [current_user.id.to_s])
    @states = {}
    @addresses.each do | address |
      @states[address.full_address] = {
          :lat => address.lat,
          :long => address.long,
          :dst => address.day_light_savings,
          :tz => Timezone[address.timezone].utc_to_local(Time.now)
      }
    end
    gon.states = @states
  end

  # Rewrite to much going on here! -jv
  def new
    @address = Address.where(:_id => country_params[:country]).first
    if(@address.blank?)
      @address = Address.new({:name => country_params[:country], :user_search => [current_user.id.to_s]})
      @address.save!
    else
      @address.user_search << current_user.id.to_s
      @address.save!
    end
    @country = Address.where(:_id => @address.country).first
    if(@country.blank?)
      @country = Address.new(:name => @address.country)
      @country.save!
    end
    respond_to do |format|
      format.html { redirect_to address_path(@country), notice: 'Address was successfully created.' }
      format.json { render :show, status: :created, location: @country }
    end
  end

  def edit
  end

  def create
    @country = Address.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Address.where(:_id => params[:id]).first
      if(@country.blank?)
        Address.new({:name => params[:id]}).save!
        @country = Address.where(:_id => params[:id]).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.permit(:name, :country)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :country_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/addresses/index.html.erb
<body class="spacer" onload="initMap()">
  <div id="map"></div>
  <div id="legend"><h3>Legend</h3></div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country %></td>
        <td><%= link_to 'Show', address_path(country) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.secrets.google_api_key %>&callback=initMap"
          async defer></script>
</body>

<script>

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 37.09024, lng: -95.712891},
            zoom: 2
        });
        var iconBase = 'https://maps.google.com/mapfiles/kml/pal3/';
        var icons = {
            day_light_savings: {
                name: 'DST',
                icon: iconBase + 'icon40.png'
            }
        };
        createLegend(map, icons);

    }

    function createLegend(map, icons){
        var legend = document.getElementById('legend');
        for (var key in icons) {
            var type = icons[key];
            var name = type.name;
            var icon = type.icon;
            var div = document.createElement('div');
            div.innerHTML = '<img src="' + icon + '"> ' + name;
            legend.appendChild(div);
        }
        map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(legend);
    }

</script>

app/views/addresses/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/addresses/show.html.erb
<body class="spacer">
    <div id="map"></div>
    <div id="legend"><h3>Legend</h3></div>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>You Searched</th>
        <th>We found</th>
        <th>Observing DST?</th>
        <th>Timezone</th>
        <th>Latitude</th>
        <th>Longitude</th>
      </tr>
      </thead>

      <tbody>
      <% @addresses.each do | address| %>
        <tr>
          <td><%= address.id%></td>
          <td><%= address.full_address %></td>
          <td><%= address.day_light_savings%></td>
          <td><%= address.timezone%></td>
          <td><%= address.lat.round(6) %></td>
          <td><%= address.long.round(6) %></td>
        </tr>
      <% end %>
      </tbody>

    </table>
    
    <%= link_to 'Back', addresses_path %>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.secrets.google_api_key %>&callback=initMap"
        async defer></script>
</body>

<script>

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: <%=@country.lat %>, lng: <%= @country.long %>},
            zoom: 4
        });

        var states = gon.states;
        var iconBase = 'https://maps.google.com/mapfiles/kml/pal3/';
        var icons = {
            day_light_savings: {
                name: 'DST',
                icon: iconBase + 'icon40.png'
            }
        };
        setMarkers(map, states);
        createLegend(map, icons);

    }

    function createLegend(map, icons){
        var legend = document.getElementById('legend');
        for (var key in icons) {
            var type = icons[key];
            var name = type.name;
            var icon = type.icon;
            var div = document.createElement('div');
            div.innerHTML = '<img src="' + icon + '"> ' + name;
            legend.appendChild(div);
        }
        map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(legend);
    }

    function setMarkers(map, states){
        Object.keys(states).forEach(function (key) {
            var value = states[key];
            console.log(key);
            console.log(value['lat']);
            var marker = new google.maps.Marker({
                position: {lat: value['lat'], lng: value['long']},
                map: map,
                title: key
            });

            var content = buildHtmlForMarker(key, value['tz'], value['dst']);

            var infowindow = new google.maps.InfoWindow();
            google.maps.event.addListener(marker, 'click', (function(marker, contentString, infowindow){
                return function(){
                    infowindow.setContent(content);
                    infowindow.open(map, marker);
                }
            })(marker, content, infowindow));
        });
    }

    function buildHtmlForMarker(key, tz, day_light_saving){
        var div = document.createElement('div');
        div.setAttribute('class', "header");
        var dst = document.createElement('img');
        dst.setAttribute('src', "https://maps.google.com/mapfiles/kml/pal3/icon40.png");
        var stateName = document.createElement('h3');
        stateName.innerText = key;
        var time = document.createElement('h4');
        time.innerText = "Time:  " + new Date(tz).toUTCString();
        var wikiLink = document.createElement('a');
        wikiLink.setAttribute('href', "https://en.wikipedia.org/wiki/" + key);
        wikiLink.innerText = "Wiki";

        if(day_light_saving){
            div.appendChild(dst);
        }
        div.appendChild(stateName);
        div.appendChild(time);
        div.appendChild(wikiLink);
        return div;
    }
</script>